### ISSUE TITLE
Running into an error

### ISSUE THREAD

**Issue by sdevo619** [jonbloom/homebridge-unifi-protect2#2]
I am running into this error when trying to connect UniFi Protect to homebridge. I see that camera-ffmpeg is a requirement for this plugin to work. Are there any additional configurations that need to be made in camera-ffmpeg, as this was what I suspect may be causing this error message. If I need to configure each camera, like camera-ffmpeg shows on their page, I am confused as to what this plugin helps with, so any clarification here would be much appreciated. Hope there is a more efficient solution, than having to configure each camera in the JSON file first, as that would be rather inefficient. Either way, I wanted to say thank you for taking time out to make this plugin. Hope I can get it to work. I do have RTSP turned on, on each camera, just to confirm that part.

I previsiously was using, and had it working, but didn't think it would work correct with UniFi Protect.
# npm install -g ffmpeg
# npm install -g homebridge-camera-ffmpeg-ufv

The error I am seeing when using your plugin:
Error: No RTSP channel found                                                                                          
    at bootstrap.cameras.map.camera (/usr/local/lib/node_modules/homebridge-ufp/index.js:162:25)                      
    at Array.map (<anonymous>)                                                                                        
    at requestPromise.get.then.response (/usr/local/lib/node_modules/homebridge-ufp/index.js:154:40)                  
    at tryCatcher (/usr/local/lib/node_modules/homebridge-ufp/node_modules/bluebird/js/release/util.js:16:23)         
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-ufp/node_modules/bluebird/js/release/

**Comment by jonbloom** [comment]
@sdevo619 The point of this plugin is to automate adding in your cameras so you don't have to manually add each camera to Homebridge, it should autodetect them. 

What devices and firmware/software version are you running UniFi Protect on?

**Comment by tobias-vdp** [comment]
@jonbloom  - same issue here - unifi protect 1.14.8 running on a dream machine pro 1.6.5 - cameras are  g3 dome / pro / micro - 4.19.4 - was running until approx 2 weeks ago

**Comment by sdevo619** [comment]
I have a bunch of different cameras, all running the latest firmwares. Still running into the same issue.

**Comment by sdevo619** [comment]
I finally got it to authenticate and add the cameras to the Home, but I running into an error every time the camera try to take snapshots. Any ideas what is causing this??

**Comment by sdevo619** [comment]
This is the current issue I am seeing

![image](https://user-images.githubusercontent.com/7008354/79697828-cf3f4b80-8239-11ea-8afc-b222a224cf12.png)

**Comment by jonbloom** [comment]
@sdevo619 Do you have ffmpeg installed?

**Comment by sdevo619** [comment]
Funny you mention it, I did a clean install of HomeBridge and on the initial reinstall, it complained about FFMPEG not being installed, and now it is giving me a depricated warning.
Here is the warning and her is the install script for the docker instance.

Install Script(Cameras and other HomeBridge devices show, but no snapshots or video on the cameras. Also tried both plain FFmpeg and homebridge-camera-ffmpeg. Which of those libraries do I need for this to work, as don't think I need both of them do i, and is there a more up to date version of either of these packages, as that may also be part of the issue here???:
apt-get update
apt-get upgrade
node --version
npm i -g npm
npm install -g homebridge

//shows deprication warning
npm install -g ffmpeg

//shows deprication warning
npm install -g homebridge-camera-ffmpeg

npm install -g homebridge-ufp

///////
![image](https://user-images.githubusercontent.com/7008354/79809178-bd86a280-8324-11ea-8b92-2f2ad35b4ac5.png)


Any ideas???

**Comment by jonbloom** [comment]
You need to have ffmpeg installed on the system, so try running `apt-get install ffmpeg`. That's really the only thing missing here, and once it's installed, it should work just fine.

The warning you're seeing is in relation to the `request` library, which this plugin uses for making HTTP requests. While I don't have any plans to swap that out (it works, and isn't going away), I may look into finding another library later on.

**Comment by sdevo619** [comment]
Still not working. Same issue as before. Could this be an error cause by having two factor turned on the main admin account, as I created a separate account for HomeBridge? Like I said I can add all the cameras to my home in the home app, using this account, but the cameras show no image and have red circle with an exclamation point in top right of the camerview window in the home app, but no video or snapshots ever comes through. That is the the only other thing I can think of right now, as it still is not working.

[UniFi Protect] An error occurs while making snapshot request

**Comment by sdevo619** [comment]
I appreciate all your help on this, but this is totally broken. I followed all your instructions to the letter, but after hours of messing around with this, I still can't get a single one of my cameras to show video or snapshots in the Home app. I had the unifi video plugin working great, with a pc as the recording box, before updating to Unifi Protect, so this is more than likely an issue with the plugin or protect, and as you will not answer me on what is responsible for the snapshot error, I am about ready to abandon your package, or go with a more custom install or another package. It's too bad as this did seem like a great solution, and it is so close, but it's inability to function, and all the dependency related issues I am having with it, its just not worth it, if I can't get any answers from you besides, all you need is FFmpeg. If you have any other ideas, I would love to hear them, but right now this package is broken.

**Comment by jonbloom** [comment]
I'm sorry you feel that way. I don't think that I'm lying when I saw I have it functioning perfectly in my environment, and others do as well. 

I'm running my setup in docker using this repo: https://github.com/oznu/docker-homebridge. 

I've written a docker-compose.yml file as well:

```yaml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:debian
    container_name: homebridge
    restart: always
    network_mode: host
    ports:
      - "8081:8081"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8081
      - PACKAGES=ffmpeg
      - CONFIG_UI_VERSION=latest
    volumes:
      - ./volumes/homebridge:/homebridge
```


Things to check: 

- RTSP enabled on each camera
- ffmpeg installed on your system
- Try accessing an RTSP feed via an external program like VLC

The requests library being deprecated is not really relevant to this, as it's only used when loading up the cameras into HomeKit, which you seem to have successfully done. The only thing that's touched after that is the video streams via ffmpeg.
